firecoders-fsa/Fire-cracker-app

server/db/models/index.js
server/db/models/order.js
server/db/models/review.js
server/db/models/user.js

completed user, order, and review models

---

package.json
server/db/index.js
server/db/models/index.js
server/db/models/order.js
server/db/models/product.js
server/db/models/review.js

successfully created models

---

package-lock.json
package.json
script/seed.js
server/db/index.js
server/db/models/product.js
server/db/models/productOrderStash.js

about to make corrections from first code review

---

package-lock.json
script/seed.js
server/db/models/image.js
server/db/models/index.js
server/db/models/product.js
server/db/models/productOrderStash.js

Manisha review updates

---

.travis.yml
README.md

this is just a test for deploying to github
---

added simple change to readme

---

script/seed.js
server/db/models/index.js
server/db/models/order.js
server/db/models/product.js

completed seeding

---

client/components/AllProducts.js
client/routes.js
client/store/index.js
client/store/products.js
script/seed.js
server/api/index.js
server/api/products.js
server/db/models/index.js

All products

---

package-lock.json
server/api/orders.js

completed delete route

---

client/components/AllProducts.js
client/components/SingleProduct.js
client/routes.js
client/store/index.js
client/store/singleProduct.js
server/api/orders.js
server/api/products.js

completed single product view

---

client/components/SingleProduct.js
script/seed.js
server/api/orders.js
server/api/products.js

corrected seed file for previous commit

---

server/api/orders.js

completed single page reviews and description updates

---

client/components/Cart.js
client/routes.js
client/store/orders.js
server/api/orders.js

Cart front end

---

script/seed.js
server/api/orders.js
server/api/users.js

completed updates to routes

---

client/components/Cart.js
client/store/orders.js
server/api/users.js

fixed store to work with new routes

---

client/components/Cart.js
server/api/orders.js
server/api/users.js
server/db/models/index.js

can view images in cart

---

client/components/Cart.js
client/components/SingleProduct.js
client/store/orders.js

did some fixes for cart

---

client/components/Cart.js
client/components/SingleProduct.js
client/components/navbar.js
client/store/orders.js
server/api/cart.js
server/api/index.js
server/api/setSessionCart.js
server/api/users.js
server/index.js

Cart quantity

---

client/components/Cart.js
client/components/ChangeQuantity.js
client/store/orders.js

can change quantity in cart

---

client/components/SingleProduct.js

fix for master

---

client/components/Cart.js
client/components/Checkout.js
client/components/CheckoutForm.js
client/components/SingleProduct.js
client/store/orders.js
server/api/cart.js

Email fixes

---

server/api/cart.js

fixed issue with cart not being a good cart

---

server/api/orders.js

added price at purchase onto stash field

---

server/api/orders.js

added minor support for inventory tracking

---

client/components/Cart.js
client/components/CheckoutForm.js

made some buttons bigger

---

client/components/Admin/AllOrders.js

Brandon finishing touches

---

client/components/AllProducts.js
client/components/SingleProduct.js
script/seed.js

fixed images
